from turtle import *
speed(50)
width(2)
def smartphone():
    penup()
    goto(100, 50)
    pendown()
    for i in range(2):
        circle(20,90)
        forward(300)
        circle(20,90)
        forward(150)
    left(90)
    penup()
    forward(30)
    pendown()
    left(90)
    for i in range(2):
        fillcolor('#0077ff')
        begin_fill()
        forward(150)
        right(90)
        forward(290)
        right(90)
        end_fill()
    penup()
    forward(75)
    pendown()
    fillcolor('black')
    begin_fill()
    circle(15)
    end_fill()
    right(90)
    penup()
    forward(295)
    right(90)
    forward(25)
    pendown()
    fillcolor('black')
    begin_fill()
    circle(5)
    end_fill()
    penup()
    left(90)
    forward(3)
    left(90)
    penup()
    forward(30)
    pendown()
    forward(50)
    left(90)
    penup()
    forward(40)
    pendown()
    for i in range(4):
        color('red')
        begin_fill()
        forward(20)
        left(90)
        end_fill()
    penup()
    left(90)
    forward(40)
    right(90)
    pendown()
    for i in range(4):
        color('yellow')
        begin_fill()
        forward(20)
        left(90)
        end_fill()
    left(90)
    penup()
    forward(40)
    right(90)
    pendown()
    for i in range(4):
        color('brown')
        forward(20)
        left(90)
    penup()
    forward(50)
    pendown()
    for i in range(4):
        color('gray')
        forward(20)
        left(90)
    right(90)
    penup()
    forward(40)
    pendown()
    left(90)
    for i in range(4):
        color('pink')
        forward(20)
        left(90)
    right(90)
    penup()
    forward(40)
    pendown()
    left(90)
    for i in range(4):
        color('indigo')
        forward(20)
        left(90)
    penup()
    forward(50)
    pendown()
    for i in range(4):
        color('blue')
        forward(20)
        left(90)
    penup()
    left(90)
    forward(40)
    right(90)
    pendown()
    for i in range(4):
        color('purple')
        forward(20)
        left(90)
    left(90)
    penup()
    forward(40)
    right(90)
    pendown()
    for i in range(4):
        color('green')
        forward(20)
        left(90)
    left(90)
    penup()
    forward(60)
    pendown()
smartphone()
exitonclick()


    